# Feature Engineering -Date Time

In [2]:
import pandas as pd
import numpy as np
import datetime as dt

In [16]:
data=pd.read_csv("/content/loan.csv",usecols=['date_issued','date_last_payment'])

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date_issued        10000 non-null  object
 1   date_last_payment  10000 non-null  object
 2   issue_dt           10000 non-null  datetime64[ns]
 3   last_payment_dt    10000 non-null  datetime64[ns]
 4   issue_date_week    10000 non-null  int64
 5   last_payment_week  10000 non-null  int64
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 468.9+ KB

In [17]:
data['issue_dt']=pd.to_datetime(data['date_issued'])
data['last_payment_dt']=pd.to_datetime(data['date_last_payment'])

# Extract Date of the Month

In [19]:
data['issue_date_week']=data['issue_dt'].dt.week
data['last_payment_week']=data['last_payment_dt'].dt.week

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

In [ ]:
data.head()

# Extract Month of the Date

In [22]:
data['issue_month']=data['issue_dt'].dt.month
data['last_payment_month']=data['last_payment_dt'].dt.month

In [23]:
data.head()

,date_issued,date_last_payment,issue_dt,last_payment_dt,issue_date_week,last_payment_week,issue_month,last_payment_month
0,2013-06-11,2016-01-14,2013-06-11,2016-01-14,24,2,6,1
1,2014-05-08,2016-01-25,2014-05-08,2016-01-25,19,4,5,1
2,2013-10-26,2014-09-26,2013-10-26,2014-09-26,43,39,10,9
3,2015-08-20,2016-01-26,2015-08-20,2016-01-26,34,4,8,1
4,2014-07-22,2016-01-11,2014-07-22,2016-01-11,30,2,7,1

# Extract Quarter

In [24]:
data['issue_quarter']=data['issue_dt'].dt.quarter
data['last_payment_quarter']=data['last_payment_dt'].dt.quarter

In [27]:
data[['issue_dt','issue_quarter']].head()

    issue_dt  issue_quarter
0 2013-06-11              2
1 2014-05-08              2
2 2013-10-26              4
3 2015-08-20              3
4 2014-07-22              3

# Extract Year

In [29]:
data['issue_year']=data['issue_dt'].dt.year
data['last_payment_year']=data['last_payment_dt'].dt.year

In [30]:
data[['issue_year','issue_dt']].head()

   issue_year   issue_dt
0        2013 2013-06-11
1        2014 2014-05-08
2        2013 2013-10-26
3        2015 2015-08-20
4        2014 2014-07-22

# Extract Day

In [31]:
data['issue_day']=data['issue_dt'].dt.day
data['last_payment_day']=data['last_payment_dt'].dt.day

In [32]:
data[['issue_day','issue_dt']].head()

   issue_day   issue_dt
0         11 2013-06-11
1          8 2014-05-08
2         26 2013-10-26
3         20 2015-08-20
4         22 2014-07-22

# Extract day of the week

In [33]:
data['issue_dayofweek']=data['issue_dt'].dt.dayofweek
data['last_payment_dayofweek']=data['last_payment_dt'].dt.dayofweek

# Extract DayName

In [34]:
data['issue_dayofweekname']=data['issue_dt'].dt.day_name()

In [36]:
data[['issue_dt','issue_dayofweekname']].head()

    issue_dt issue_dayofweekname
0 2013-06-11             Tuesday
1 2014-05-08            Thursday
2 2013-10-26            Saturday
3 2015-08-20            Thursday
4 2014-07-22             Tuesday

In [37]:
data['issue_dt_is_weekend'] = np.where(data['issue_dayofweekname'].isin(['Sunday', 'Saturday']), 1,0)

In [38]:
data[['issue_dt_is_weekend','issue_dayofweekname','issue_dt']].head()

   issue_dt_is_weekend issue_dayofweekname   issue_dt
0                    0             Tuesday 2013-06-11
1                    0            Thursday 2014-05-08
2                    1            Saturday 2013-10-26
3                    0            Thursday 2015-08-20
4                    0             Tuesday 2014-07-22

#Extract Time elapsed between dates

In [40]:
data['time_elpased']=data['issue_dt']-data['last_payment_dt']

In [41]:
data[['time_elpased','issue_dt','last_payment_dt']].head()

  time_elpased   issue_dt last_payment_dt
0    -947 days 2013-06-11      2016-01-14
1    -627 days 2014-05-08      2016-01-25
2    -335 days 2013-10-26      2014-09-26
3    -159 days 2015-08-20      2016-01-26
4    -538 days 2014-07-22      2016-01-11

# calculate number of months passed between 2 dates

In [42]:
data['time_elpased']=(data['issue_dt']-data['last_payment_dt'])/ np.timedelta64(1, 'M')

In [43]:
data[['time_elpased','issue_dt','last_payment_dt']]

      time_elpased   issue_dt last_payment_dt
0       -31.113575 2013-06-11      2016-01-14
1       -20.600012 2014-05-08      2016-01-25
2       -11.006386 2013-10-26      2014-09-26
3        -5.223927 2015-08-20      2016-01-26
4       -17.675928 2014-07-22      2016-01-11
...            ...        ...             ...
9995     -9.626481 2010-01-14      2010-11-03
9996    -10.250724 2015-03-20      2016-01-26
9997     -8.312286 2015-04-03      2015-12-12
9998    -13.273373 2014-11-23      2016-01-01
9999    -11.893468 2015-01-19      2016-01-16

[10000 rows x 3 columns]