In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from feature_engine.encoding import OneHotEncoder as fe_OneHotEncoder
#from sklearn.preprocessing import StandardScaler
%matplotlib inline
sns.set_style("whitegrid")

In [4]:
def read_data():
 heart_dis_df=pd.read_csv(r"/content/heart_disrease.csv")
 return heart_dis_df

In [6]:
def identify_variable_type(heart_dis_df):
    categorical_val1 = []
    continous_val1 = []
    for column in heart_dis_df.columns:
        #print(f"{column} : {heart_dis_df[column].unique()}")
        if heart_dis_df[column].nunique() <= 10:
            categorical_val1.append(column)
        else:
            continous_val1.append(column)
    return categorical_val1,continous_val1

In [10]:
heart_dis_df=read_data()

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    heart_dis_df.drop('target',axis=1),  # predictors
    heart_dis_df['target'],  # target
    test_size=0.3,  # percentage of obs in test set
    random_state=0)  # seed to ensure reproducibility

X_train.shape, X_test.shape

((212, 13), (91, 13))

In [28]:
for j in ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']:
  X_train[j].apply(str)

In [32]:
ohe_enc = fe_OneHotEncoder(
    top_categories=None,
    variables=['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal'],  # we can select which variables to encode
    drop_last=True)  # to return k-1, false to return k



#ohe_enc.fit(X_train['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal'].fillna('Missing'))

In [42]:
for j in ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']:
  X_train[j]= X_train[j].apply(str)
  X_test[j]= X_test[j].apply(str)
train=ohe_enc.fit_transform(X_train.fillna('Missing'))

In [43]:
test=ohe_enc.fit_transform(X_test.fillna('Missing'))

In [44]:
train.isnull().sum(),train.shape

(age          0
 trestbps     0
 chol         0
 thalach      0
 oldpeak      0
 sex_1        0
 cp_1         0
 cp_3         0
 cp_0         0
 fbs_1        0
 restecg_0    0
 restecg_1    0
 exang_0      0
 slope_2      0
 slope_1      0
 ca_0         0
 ca_1         0
 ca_3         0
 ca_2         0
 thal_2       0
 thal_3       0
 thal_1       0
 dtype: int64, (212, 22))

In [45]:
train.head(2)

,age,trestbps,chol,thalach,oldpeak,sex_1,cp_1,cp_3,cp_0,fbs_1,...,exang_0,slope_2,slope_1,ca_0,ca_1,ca_3,ca_2,thal_2,thal_3,thal_1
137,62,128,208,140,0.0,1,1,0,0,1,...,1,1,0,1,0,0,0,1,0,0
106,69,160,234,131,0.1,1,0,1,0,1,...,1,0,1,0,1,0,0,1,0,0

In [46]:
s_sc = StandardScaler()
col_to_scale = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
train[col_to_scale] = s_sc.fit_transform(train[col_to_scale])

In [47]:
train.head(2)

,age,trestbps,chol,thalach,oldpeak,sex_1,cp_1,cp_3,cp_0,fbs_1,...,exang_0,slope_2,slope_1,ca_0,ca_1,ca_3,ca_2,thal_2,thal_3,thal_1
137,0.835114,-0.206649,-0.718763,-0.429839,-0.907178,1,1,0,0,1,...,1,1,0,1,0,0,0,1,0,0
106,1.616520,1.727014,-0.250130,-0.827575,-0.823777,1,0,1,0,1,...,1,0,1,0,1,0,0,1,0,0

In [ ]:
! pip install feature_engine