In [3]:
from sklearn.impute import SimpleImputer 
from sklearn.compose import ColumnTransformer
from sklearn.pipeline  import Pipeline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df_housing=pd.read_csv(r"/content/my_data/train.csv")

In [6]:
df_housing.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
data=df_housing[['Age','Fare','Survived']]

In [8]:
def impute_na(df,variable,mean_med):
    return df[variable].fillna(mean_med)

In [9]:
mead=data['Age'].median()
mn=data['Age'].mean()

In [ ]:
data['Age_Median']=impute_na(data,'Age',mead)
data['Age_Mean']=impute_na(data,'Age',mn)

In [11]:
data.head()

    Age     Fare  Survived  Age_Median  Age_Mean
0  22.0   7.2500         0        22.0      22.0
1  38.0  71.2833         1        38.0      38.0
2  26.0   7.9250         1        26.0      26.0
3  35.0  53.1000         1        35.0      35.0
4  35.0   8.0500         0        35.0      35.0

In [24]:
 col = [
'OverallQual',
'TotalBsmtSF', 
#'IstFirSF', 
'GrLivArea', 
'WoodDeckSF',
'BsmtUnfSF', 
'LotFrontage', 
'MasVnrArea', 
'GarageYrBlt', 
'SalePrice'
]

In [25]:

df=pd.read_csv(r"/content/my_data/train1.csv",usecols=col)

In [49]:
df.columns

Index(['LotFrontage', 'OverallQual', 'MasVnrArea', 'BsmtUnfSF', 'TotalBsmtSF',
       'GrLivArea', 'GarageYrBlt', 'WoodDeckSF', 'SalePrice'],
      dtype='object')

In [26]:
df.shape

(1460, 9)

In [27]:
df.isnull().sum()

LotFrontage    259
OverallQual      0
MasVnrArea       8
BsmtUnfSF        0
TotalBsmtSF      0
GrLivArea        0
GarageYrBlt     81
WoodDeckSF       0
SalePrice        0
dtype: int64

In [50]:
numeric_feature_mean=['LotFrontage']
numeric_feature_median=['MasVnrArea','GarageYrBlt']

In [29]:
#Set Pipeline

In [51]:
numeric_mean_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy='mean'))])
numeric_median_imputer=Pipeline(steps=[('imputer',SimpleImputer(strategy='median'))])

In [ ]:
# Pass the Pipeline to Column Transformer

In [54]:
preprocessor=ColumnTransformer(transformers=[('mean_imputer',numeric_feature_mean,numeric_mean_imputer),
                                             ('median_imputer',numeric_feature_median,numeric_median_imputer)],
                               remainder='passthrough')

In [55]:
preprocessor.fit(df)

TypeError: ignored

In [57]:
data=preprocessor.transform(data)
data.isnull.mean()

AttributeError: ignored